
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalisisHTML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int diagonal = 10;
  public static final int cadena = 13;
  public static final int mayorque = 9;
  public static final int rdiv = 6;
  public static final int EOF = 0;
  public static final int rhtml = 2;
  public static final int rbody = 12;
  public static final int error = 1;
  public static final int rtitle = 4;
  public static final int rhead = 3;
  public static final int rid = 7;
  public static final int igual = 11;
  public static final int menorque = 8;
  public static final int rnoufe = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "rhtml",
  "rhead",
  "rtitle",
  "rnoufe",
  "rdiv",
  "rid",
  "menorque",
  "mayorque",
  "diagonal",
  "igual",
  "rbody",
  "cadena"
  };
}

