
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int id = 13;
  public static final int puntocoma = 8;
  public static final int coma = 7;
  public static final int suma = 9;
  public static final int cadena = 14;
  public static final int decimal = 3;
  public static final int imprimir = 10;
  public static final int EOF = 0;
  public static final int asignacion = 6;
  public static final int pari = 12;
  public static final int entero = 2;
  public static final int error = 1;
  public static final int booleano = 4;
  public static final int pard = 11;
  public static final int var = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "entero",
  "decimal",
  "booleano",
  "var",
  "asignacion",
  "coma",
  "puntocoma",
  "suma",
  "imprimir",
  "pard",
  "pari",
  "id",
  "cadena"
  };
}

